---

Transform: AWS::Serverless-2016-10-31

Parameters:
  StravaClientId:
    Type: String
    NoEcho: true
  StravaClientSecret:
    Type: String
    NoEcho: true
  StravaRefreshToken:
    Type: String
    NoEcho: true
  StravaVerifyToken:
    Type: String
    NoEcho: true
    Default: a_string_used_for_authentication

Resources:
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api.template.yaml
      Parameters:
        RootStackName: !Ref AWS::StackName
        StravaApiUrl: https://www.strava.com/api/v3
        StravaClientId: !Ref StravaClientId
        StravaClientSecret: !Ref StravaClientSecret
        StravaRefreshToken: !Ref StravaRefreshToken
        StravaVerifyToken: !Ref StravaVerifyToken

  StravaSubscriptionCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: strava_subscription_custom_resource_function.main.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          API_CALLBACK_URL: !GetAtt ApiStack.Outputs.Url
          STRAVA_API_URL: https://www.strava.com/api/v3
          STRAVA_VERIFY_TOKEN: !Ref StravaVerifyToken

  StravaSubscription:
    Type: Custom::StravaSubscription
    Properties:
      ServiceTimeout: 10
      ServiceToken: !GetAtt StravaSubscriptionCustomResourceFunction.Arn
      ClientId: !Ref StravaClientId
      ClientSecret: !Ref StravaClientSecret
