---

name: Verify

"on": [push]

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@v2
      - run: cfn-lint

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
